version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dupl
    - errcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - godot
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - goconst
          - revive
        path: _test\.go
      - linters:
          - revive
        text: dot-imports
    paths:
      - third_party$
      - builtin$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
