{
 "title": "CRD Conditions Browser",
 "description": "Dashboard to monitor operator custom resource conditions",
 "tags": [ "ocf" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Operator (scrape job)",
    "query": {
     "query": "label_values({{operator_namespace}}controller_condition,job)"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "label_values({{operator_namespace}}controller_condition{job=~\"$job\"},kind)"
    }
   },
   {
    "name": "condition",
    "label": "Condition",
    "query": {
     "query": "label_values({{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\"},condition)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": {
     "query": "label_values({{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\"},status)"
    }
   },
   {
    "name": "reason",
    "label": "Reason",
    "query": {
     "query": "label_values({{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", status=~\"$status\"},reason)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(sum ({{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\"} > 0) by ({{namespace_label}}))"
    }
   },
   {
    "name": "resource_id",
    "label": "Resource",
    "query": {
     "query": "label_values({{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", status=~\"$status\", reason=~\"$reason\", {{namespace_label}}=~\"$namespace\"},id)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Operator Conditions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Conditions Matching",
   "type": "stat",
   "description": "Conditions matching the given filter criteria ",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n    {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", status=~\"$status\", reason=~\"$reason\", id=~\"$resource_id\", {{namespace_label}}=~\"$namespace\"} > 0\n  and\n    topk by (id, condition) (1, {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", {{namespace_label}}=~\"$namespace\"})\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$kind Conditions",
   "type": "table",
   "description": "Table of $kind conditions of type $condition",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(\n  {{operator_namespace}}controller_condition{job=~\"$job\", \n    kind=\"$kind\",\n    condition=~\"$condition\",\n    status=~\"$status\",\n    reason=~\"$reason\",\n    id=~\"$resource_id\",\n    {{namespace_label}}=~\"$namespace\"\n  }\n  and\n  topk by (id, condition) (1, {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", {{namespace_label}}=~\"$namespace\"})\n) by (name, {{namespace_label}}, condition, status, reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Counts Per Condition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$condition=False",
     "type": "stat",
     "description": "Number of $kind $condition Conditions with status False",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
     "repeat": "condition",
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n    {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", status=\"False\", reason=~\"$reason\", id=~\"$resource_id\", {{namespace_label}}=~\"$namespace\"} > 0\n  and\n    topk by (id, condition) (1, {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", {{namespace_label}}=~\"$namespace\"})\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$condition=Unknown",
     "type": "stat",
     "description": "Number of $kind $condition Conditions with status Unknown",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "repeat": "condition",
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n    {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", status=\"Unknown\", reason=~\"$reason\", id=~\"$resource_id\", {{namespace_label}}=~\"$namespace\"} > 0\n  and\n    topk by (id, condition) (1, {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", {{namespace_label}}=~\"$namespace\"})\n)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$condition=True",
     "type": "stat",
     "description": "Number of $kind $condition Conditions with status True",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "repeat": "condition",
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n    {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", status=\"True\", reason=~\"$reason\", id=~\"$resource_id\", {{namespace_label}}=~\"$namespace\"} > 0\n  and\n    topk by (id, condition) (1, {{operator_namespace}}controller_condition{job=~\"$job\", kind=\"$kind\", condition=~\"$condition\", {{namespace_label}}=~\"$namespace\"})\n)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  }
 ]
}