name: Compatibility

on:
  schedule:
    - cron: "0 8 * * 1" # Every Monday at 08:00 UTC
  workflow_dispatch:
  pull_request:
    types: [labeled]

jobs:
  compatibility:
    if: >-
      github.event_name != 'pull_request' ||
      github.event.label.name == 'compatibility'
    name: "CR v${{ matrix.controller-runtime }} / k8s v${{ matrix.k8s }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - controller-runtime: "0.23"
            cr-version: "v0.23.3"
            k8s: "0.35"
            k8s-version: "v0.35.2"
            current: true
          - controller-runtime: "0.22"
            cr-version: "v0.22.0"
            k8s: "0.34"
            k8s-version: "v0.34.0"
            current: false
          - controller-runtime: "0.21"
            cr-version: "v0.21.0"
            k8s: "0.33"
            k8s-version: "v0.33.0"
            current: false
          - controller-runtime: "0.20"
            cr-version: "v0.20.0"
            k8s: "0.32"
            k8s-version: "v0.32.0"
            current: false
          - controller-runtime: "0.19"
            cr-version: "v0.19.0"
            k8s: "0.31"
            k8s-version: "v0.31.0"
            current: false
          - controller-runtime: "0.18"
            cr-version: "v0.18.0"
            k8s: "0.30"
            k8s-version: "v0.30.0"
            current: false
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Swap dependencies
        if: ${{ !matrix.current }}
        run: |
          go get \
            sigs.k8s.io/controller-runtime@${{ matrix.cr-version }} \
            k8s.io/api@${{ matrix.k8s-version }} \
            k8s.io/apimachinery@${{ matrix.k8s-version }} \
            k8s.io/client-go@${{ matrix.k8s-version }} \
            k8s.io/apiextensions-apiserver@${{ matrix.k8s-version }} \
            k8s.io/utils@latest
          go mod tidy

      - name: Verify compilation
        run: go build ./...

      - name: Build examples
        run: make build-examples

      - name: Run tests
        run: make test
